export CUDA_VISIBLE_DEVICES=1,2,3,4
export REWARD_CUDA_VISIBLE_DEVICES=4
export WANDB_API_KEY="b8f38344ec7231ee89baa74ef7209dd5a43df6b2"
export WANDB_ENTITY="mhong-university-of-minnesota"

python3 -m verl.trainer.main_ppo \
 +trainer.project_name=CudaForge_RL \
 +trainer.experiment_name="d1213_dapo_kernelbenchlevel1_16K_Hongserver" \
 algorithm.adv_estimator=grpo \
 data.train_files=./dataset/CudaForge/Level1/train.parquet \
 data.val_files=./dataset/CudaForge/Level1/test.parquet \
 data.train_batch_size=16 \
 data.max_prompt_length=8192 \
 data.max_response_length=16384 \
 actor_rollout_ref.model.path=./Qwen3_8b \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=8 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=16 \
 actor_rollout_ref.rollout.name=vllm \
 actor_rollout_ref.rollout.n=8 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.3 \
 critic.optim.lr=1e-5 \
 critic.model.path=/home/zha00175/data/Qwen3_8b \
 critic.ppo_micro_batch_size_per_gpu=4 \
 reward_model.enable=False \
 reward_model.reward_manager=dapo \
 algorithm.kl_ctrl.kl_coef=0 \
 trainer.val_before_train=False \
 trainer.n_gpus_per_node=1 \
 trainer.nnodes=1 \
 trainer.save_freq=75 \
 trainer.test_freq=75 \
 trainer.total_epochs=15 2>&1 | tee verl_demo.log \
 trainer.logger='["console","wandb"]' \
 trainer.project_name="DAPO" \
 trainer.experiment_name="d1213_DAPO_kernelbenchlevel1_topp080" \