export CUDA_VISIBLE_DEVICES=0,1,2,3
export REWARD_CUDA_VISIBLE_DEVICES=3
export WANDB_API_KEY="b8f38344ec7231ee89baa74ef7209dd5a43df6b2"
export WANDB_ENTITY="mhong-university-of-minnesota"
export Model_path="/code/hongpaul-sandbox/temp/CudaForge_plus/verl/data/Qwen3_8b"

max_response_length=16384

# export VLLM_ATTENTION_BACKEND=XFORMERS

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 trainer.project_name=CudaForge_RL \
 algorithm.adv_estimator=grpo \
 data.train_files=./dataset/CudaForge/Level1/train.parquet \
 data.val_files=./dataset/CudaForge/Level1/test.parquet \
 data.train_batch_size=16 \
 data.max_prompt_length=8192 \
 data.max_response_length=16384 \
 actor_rollout_ref.model.path=$Model_path \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=16 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.name=vllm \
 actor_rollout_ref.rollout.n=8 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
 actor_rollout_ref.actor.fsdp_config.param_offload=False \
 actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
 actor_rollout_ref.rollout.temperature=0.6 \
 actor_rollout_ref.rollout.top_k=20 \
 actor_rollout_ref.rollout.top_p=0.95 \
 actor_rollout_ref.actor.clip_ratio_low=0.2 \
 actor_rollout_ref.actor.clip_ratio_high=0.28 \
 critic.optim.lr=1e-5 \
 critic.model.path=/home/zha00175/data/Qwen3_8b \
 critic.ppo_micro_batch_size_per_gpu=4 \
 reward_model.enable=False \
 reward_model.reward_manager=dapo \
 custom_reward_function.path=./verl/utils/reward_score/CudaForge.py \
 algorithm.kl_ctrl.kl_coef=0 \
 trainer.val_before_train=False \
 trainer.n_gpus_per_node=4 \
 trainer.nnodes=1 \
 trainer.save_freq=20 \
 trainer.test_freq=100 \
 trainer.total_epochs=20 2>&1 | tee verl_demo.log \
 trainer.logger='["console","wandb"]' \
 trainer.project_name="DAPO" \
 trainer.experiment_name="d1214r1_DAPO_kernelbenchlevel1_topp095" \